In [212]:
# ライブラリのインポート
from datetime import datetime, timedelta
import talib as ta
import numpy as np
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
import seaborn as sns
%matplotlib inline
import warnings
warnings.simplefilter('ignore')

In [213]:
def import_data(kind, reference='yahoo'):
    data_master = data.DataReader(kind, reference, '2000-01-01', end)
    data_master.reset_index(drop=False, inplace=True)
    data_master['Date'] = pd.to_datetime(data_master['Date'])
    return data_master

In [214]:
# 開始日時と終了日時
start, end = '2021-01-01', '2021-12-01'
# 使用する銘柄
kind = '^N225'

In [215]:
# データのインポートを行う
data_master = import_data(kind=kind)

In [216]:
# Dateをインデックスに指定
data_master.set_index('Date',inplace=True)
data_master

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2000-01-04,19187.609375,18937.449219,18937.449219,19002.859375,0.0,19002.859375
2000-01-05,19003.509766,18221.820312,19003.509766,18542.550781,0.0,18542.550781
2000-01-06,18582.740234,18168.269531,18574.009766,18168.269531,0.0,18168.269531
2000-01-07,18285.730469,18068.099609,18194.050781,18193.410156,0.0,18193.410156
2000-01-11,18887.560547,18246.099609,18246.099609,18850.919922,0.0,18850.919922
...,...,...,...,...,...,...
2021-11-25,29570.419922,29444.449219,29469.650391,29499.279297,50700000.0,29499.279297
2021-11-26,29332.990234,28605.609375,29324.470703,28751.619141,72900000.0,28751.619141
2021-11-29,28776.339844,28187.119141,28337.960938,28283.919922,85900000.0,28283.919922
2021-11-30,28718.699219,27819.140625,28611.730469,27821.759766,140700000.0,27821.759766
2021-12-01,28106.300781,27594.009766,27866.730469,27935.619141,80900000.0,27935.619141

In [217]:
# windows: 移動平均日数
windows = [2, 3, 5, 10, 20, 40, 80]
# macd_windows: MACD用の移動平均日数
macd_windows = [10, 20, 30]
# deviation: ボリンジャーバンド用の偏差
deviation = [1, 2, 3]
# rsi_upper, rsi_lower: RSIの買いすぎ売られすぎ指標
rsi_upper, rsi_lower = 70, 30
# di_span, dx_span: DI,DXの計算期間日数
di_span, dx_span = 14, 14

# データのインポートを行う
data_master = import_data(kind=kind)
# テクニカル指標を作成
# data_technical, data_logic, data_graph = data_arrange(data_master)

In [382]:
data_technical=data_master.copy()
data_technical.set_index('Date',inplace=True)
# s = data_technical['Close']

logic_counter = gen_counter()
data_graph = []
# data_logic_no_stack=[]
# data_logic_name_stack=[]
data_logic_complile=[]
data_graph = []

GCDC_signal_COL=[]
MACD_signal_COL=[]
RSI_signal_COL=[]
bollingerBands_signal_COL=[]
GCDC_MACD_signal=[]


def gen_counter():
    """呼び出すごとにカウントを上げるカウンタを生成する"""
    # クロージャ _counter で利用する現在のカウント
    count = 0
    def _counter(reset=False):        
        nonlocal count # 関数の外にある count を更新したいので nonlocal 宣言をする
        if reset:
            count = 0
        count += 1
        return count
    return _counter

def Average_SMA(data,prices,window):
    for i in window:
        data['sma_'+str(i)]=prices.rolling(window=i).mean()
    return data

def Average_EMA(data,prices,window):
    for i in window:
        data['ema_'+str(i)]=prices.ewm(span=i).mean()
    return data

def RSI(data,prices,window):
    for i in window:
        data['rsi_' + str(i)] = ta.RSI(prices, timeperiod=i)
    return data

def bollingerBands(data,prices,window):
    data_sma=Average_SMA(data=data,prices=data[['Close']],window=windows)   
    for i in window:    
        for j in deviation:
            # upper_sigma
            data['upper_' + str(i) + '_dev_' + str(j)] = data_sma['sma_' + str(i)] + data['Close'].rolling(window=i).std(ddof=0) * j
            #lower_sigma
            data['lower_' + str(i) + '_dev_' + str(j)] = data_sma['sma_' + str(i)] - data['Close'].rolling(window=i).std(ddof=0) * j

            # ボリンジャーバンドの上か下か
            data['upper_check' + str(i) + '_dev_' + str(j)] = data['Close'] >= data['upper_' + str(i) + '_dev_' + str(j)]
            data['lower_check' + str(i) + '_dev_' + str(j)] = data['Close'] <= data['lower_' + str(i) + '_dev_' + str(j)]
    return data


# 実体
def Candlestick_entity(data):
    data['entity'] = abs(data['Open'] - data['Close'])
    return data

# ローソクの長さ
def Candlestick_size(data):
    data['size'] = data['High'] - data['Low']
    return data

# True＝陽
def Candlestick_Yin_yang(data):
    data['陽陰'] = data['Close'] > data['Open']
    return data

# 上ヒゲの長さ
def Candlestick_upper_hige(data):
    data['upper_hige'] = data.apply(lambda x: (x['High'] - x['Close']) if x['Close'] >= x['Open'] else (x['High'] - x['Open']),axis=1)
    return data

# 下ヒゲの長さ
def Candlestick_lower_hige(data):
    data['lower_hige'] = data.apply(lambda x: (x['Open'] - x['Low'] ) if x['Close'] >= x['Open'] else (x['Close'] - x['Low']),axis=1)
    return data

# 上ヒゲ、実体、下ヒゲのpercentage
def Candlestick_size_percentage(data):
    size_ = Candlestick_size(data)['size']
    upper_hige_ = Candlestick_upper_hige(data)['upper_hige']
    entity_ = Candlestick_entity(data)['entity']
    lower_hige_ = Candlestick_lower_hige(data)['lower_hige'] 
    
    data['upper_size'] = upper_hige_ / size_
    data['entity_seze'] = entity_ / size_
    data['lower_size'] =  lower_hige_ / size_

    return data


def DM(data):
    pos_DM = (data['High'] - data['High'].shift(1))
    neg_DM = (data['Low'].shift(1) - data['Low'])
    pos_DM.loc[pos_DM < 0] = 0
    pos_DM.loc[pos_DM - neg_DM < 0] = 0
    neg_DM.loc[neg_DM < 0] = 0
    neg_DM.loc[neg_DM - pos_DM < 0] = 0
    return pos_DM,neg_DM

def TrueRange(data):
    high_low = (data['High'] - data['Low']).abs()
    high_yest_close = (data['High'] - data['Close'].shift(1)).abs()
    low_yest_close = (data['Low'] - data['Close'].shift(1)).abs()
    tr = pd.concat([high_low, high_yest_close, low_yest_close], axis=1).max(axis=1)
    return tr

def DMI(data):
    tr=TrueRange(data)
    pos_DM,neg_DM=DM(data)
    
    data['+DI'] = pos_DM.rolling(di_span).sum() / tr.rolling(di_span).sum() * 100
    data['-DI'] = neg_DM.rolling(di_span).sum() / tr.rolling(di_span).sum() * 100
    data['DX'] = (data_technical['+DI'] - data_technical['-DI']) / (data_technical['+DI'] + data_technical['-DI'])
    data['ADX'] = data_technical['DX'].ewm(span=dx_span).mean()
    data['ADX_diff'] = data_technical['ADX'].diff(1)
    return data


def GCDC_signal(data):
    data=Average_SMA(data=data,prices=s,window=windows)
    for i in windows[::-1]:
        for j in windows:
            if i>j:
                n=logic_counter()
                logic1 = 'logic' + str('{0:05d}'.format(n))
                data['sma_' + str(i)+'-'+str(j)] = data['sma_' + str(i)] - data['sma_'+str(j)]

                data[logic1 + '_sell'] = (data['sma_' + str(i) + '-' + str(j)] * data['sma_' + str(i) + '-' + str(j)].shift(1) < 0) & (data['sma_'+str(i)] > data['sma_'+str(j)])
                data[logic1 + '_buy'] = (data['sma_' + str(i) + '-' + str(j)] * data['sma_' + str(i) + '-' + str(j)].shift(1) < 0) & (data['sma_' + str(i)] < data['sma_'+str(j)])
                data_logic_complile.append([logic1,'sma_' + str(i)+'-'+str(j)])
                GCDC_signal_COL.append([logic1,'sma_' + str(i)+'-'+str(j),i,j])
#                 data_logic_no_stack.append(logic1)
#                 data_logic_name_stack.append('sma_' + str(i)+'-'+str(j))
#                 p(logic1)
#                 data_logic2 = pd.concat([data_logic2, pd.DataFrame([logic1, 'sma_slope_' + str(i) + '-' + str(j)]).T])
                data_graph.append([logic1, ['sma_' + str(i), 'sma_' + str(j)]])
    return data


def MACD_signal(data):
    for k in macd_windows[::-1]:
        for l in macd_windows:
            if k > l:
                # MACDの買いシグナルと売りシグナル
                n=logic_counter()
                logic2 = 'logic' + str('{0:05d}'.format(n))
                macd, macdsignal, macdhist = ta.MACD(data['Close'], fastperiod=l, slowperiod=k, signalperiod=l)
                data['macd_'+ str(k)+'-'+str(l)] = macd
                data['macdsignal_'+ str(k)+'-'+str(l)] = macdsignal
                data['macdhist_'+ str(k)+'-'+str(l)] = macdhist
                data[logic2 + '_sell'] = ((data['macdhist_'+ str(k)+'-'+str(l)].shift(1) > 0) & (data['macdhist_'+ str(k)+'-'+str(l)] < 0))
                data[logic2 + '_buy'] = ((data['macdhist_'+ str(k)+'-'+str(l)].shift(1) <= 0) & (data['macdhist_'+ str(k)+'-'+str(l)] >= 0))       
                data_logic_complile.append([logic2,'MACD_' + str(k) + '-' + str(l)])
                MACD_signal_COL.append([logic2,'MACD_' + str(k) + '-' + str(l),k,l])
                data_graph.append([logic2, ['macd_'+ str(k)+'-'+str(l), 'macdsignal_'+ str(k)+'-'+str(l), 'macdhist_'+ str(k)+'-'+str(l)]])               
    return data


def GCDC_MACD_signal(data):
    for i in range(len(GCDC_signal_COL)):
        for j in range(len(MACD_signal_COL)):
            n=logic_counter()
            logic1=GCDC_signal_COL[i][0]
            logic2=MACD_signal_COL[j][0]

            logic5 = 'logic' + str('{0:05d}'.format(n))
            data[logic5 + '_sell'] = (data[logic1 + '_sell'] == True) & (data[logic2 + '_sell'] == True)
            data[logic5 + '_buy'] = (data[logic1 + '_buy'] == True) & (data[logic2 + '_buy'] == True)

            data_logic_complile.append([logic5, 'sma_slope_'+str(GCDC_signal_COL[i][2])+'-'+str(GCDC_signal_COL[i][3])+'_macdhist_'+ str(MACD_signal_COL[j][2])+'-'+str(MACD_signal_COL[j][3])])
#             GCDC_MACD_signal.append(logic5)

#             data_graph.append([logic5, ['sma_' + str(GCDC_signal_COL[i][2]), 'sma_' + str(GCDC_signal_COL[i][3]), 'macdhist_'+ MACD_signal_COL[j][2]+'-'+MACD_signal_COL[j][3]]])
    return data

def TrueFalseConversion(data):
    data.replace({False: 0, True: 1}, inplace=True)
    return data

def Data_Extraction(data,start):
    data.reset_index(drop=False, inplace=True)
    start_timestamp= pd.to_datetime(start)
    data = data.set_index('Date')
    data = data.loc[start_timestamp:, :]
    data.reset_index(drop=False, inplace=True)        
    return data

In [383]:
data_technical=Average_SMA(data=data_technical,prices=s,window=windows)
data_technical=Average_EMA(data=data_technical,prices=s,window=windows)
data_technical=RSI(data=data_technical,prices=s,window=windows)
data_technical=bollingerBands(data=data_technical,prices=s,window=windows)
data_technical=Candlestick_entity(data_technical)
data_technical=Candlestick_size(data_technical)
data_technical=Candlestick_Yin_yang(data_technical)
data_technical=Candlestick_upper_hige(data_technical)
data_technical=Candlestick_lower_hige(data_technical)
data_technical=Candlestick_size_percentage(data_technical)
data_technical=DMI(data_technical)
data_technical=GCDC_signal(data_technical)
data_technical=MACD_signal(data_technical)
# data_technical=GCDC_MACD_signal(data_technical)
data_technical

,High,Low,Open,Close,Volume,Adj Close,sma_2,sma_3,sma_5,sma_10,...,macd_30-20,macdsignal_30-20,macdhist_30-20,logic00023_sell,logic00023_buy,macd_20-10,macdsignal_20-10,macdhist_20-10,logic00024_sell,logic00024_buy
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,19187.609375,18937.449219,18937.449219,19002.859375,0.0,19002.859375,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-05,19003.509766,18221.820312,19003.509766,18542.550781,0.0,18542.550781,18772.705078,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-06,18582.740234,18168.269531,18574.009766,18168.269531,0.0,18168.269531,18355.410156,18571.226562,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-07,18285.730469,18068.099609,18194.050781,18193.410156,0.0,18193.410156,18180.839844,18301.410156,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-11,18887.560547,18246.099609,18246.099609,18850.919922,0.0,18850.919922,18522.165039,18404.199870,18551.601953,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-25,29570.419922,29444.449219,29469.650391,29499.279297,50700000.0,29499.279297,29400.969727,29525.349609,29584.115625,29608.165820,...,96.493981,76.235202,20.258779,False,False,104.810882,134.398935,-29.588053,False,False
2021-11-26,29332.990234,28605.609375,29324.470703,28751.619141,72900000.0,28751.619141,29125.449219,29184.519531,29414.707422,29555.541797,...,69.050917,75.550984,-6.500068,True,False,25.959173,114.682615,-88.723442,False,False
2021-11-29,28776.339844,28187.119141,28337.960938,28283.919922,85900000.0,28283.919922,28517.769531,28844.939453,29122.317578,29422.936719,...,31.030461,71.310934,-40.280473,False,False,-73.354521,80.494045,-153.848566,False,False
2021-11-30,28718.699219,27819.140625,28611.730469,27821.759766,140700000.0,27821.759766,28052.839844,28285.766276,28731.847656,29227.432617,...,-15.538811,63.039530,-78.578341,False,False,-185.616108,32.110380,-217.726489,False,False
2021-12-01,28106.300781,27594.009766,27866.730469,27935.619141,80900000.0,27935.619141,27878.689453,28013.766276,28458.439453,29040.182617,...,-51.361124,52.144230,-103.505354,False,False,-255.646756,-20.209099,-235.437657,False,False

In [384]:
data_technical=GCDC_MACD_signal(data_technical)
data_technical

,High,Low,Open,Close,Volume,Adj Close,sma_2,sma_3,sma_5,sma_10,...,logic00083_sell,logic00083_buy,logic00084_sell,logic00084_buy,logic00085_sell,logic00085_buy,logic00086_sell,logic00086_buy,logic00087_sell,logic00087_buy
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,19187.609375,18937.449219,18937.449219,19002.859375,0.0,19002.859375,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
2000-01-05,19003.509766,18221.820312,19003.509766,18542.550781,0.0,18542.550781,18772.705078,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
2000-01-06,18582.740234,18168.269531,18574.009766,18168.269531,0.0,18168.269531,18355.410156,18571.226562,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
2000-01-07,18285.730469,18068.099609,18194.050781,18193.410156,0.0,18193.410156,18180.839844,18301.410156,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
2000-01-11,18887.560547,18246.099609,18246.099609,18850.919922,0.0,18850.919922,18522.165039,18404.199870,18551.601953,NaN,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-25,29570.419922,29444.449219,29469.650391,29499.279297,50700000.0,29499.279297,29400.969727,29525.349609,29584.115625,29608.165820,...,False,False,False,False,False,False,False,False,False,False
2021-11-26,29332.990234,28605.609375,29324.470703,28751.619141,72900000.0,28751.619141,29125.449219,29184.519531,29414.707422,29555.541797,...,False,False,False,False,False,False,False,False,False,False
2021-11-29,28776.339844,28187.119141,28337.960938,28283.919922,85900000.0,28283.919922,28517.769531,28844.939453,29122.317578,29422.936719,...,False,False,False,False,False,False,False,False,False,False
2021-11-30,28718.699219,27819.140625,28611.730469,27821.759766,140700000.0,27821.759766,28052.839844,28285.766276,28731.847656,29227.432617,...,False,False,False,False,False,False,False,False,False,False
2021-12-01,28106.300781,27594.009766,27866.730469,27935.619141,80900000.0,27935.619141,27878.689453,28013.766276,28458.439453,29040.182617,...,False,False,False,False,False,False,False,False,False,False

In [389]:
data_logic = pd.DataFrame(data_logic_complile, columns=['logic_number','logic_name'])
data_logic.to_csv('logc list.csv')
data_logic

# df_merge2=list(zip(data_logic_no_stack,data_logic_name_stack))
# df_merge2
# df_merge3=pd.DataFrame(df_merge2, columns=['logic_number','logic_name'])
# df_merge3

   logic_number                    logic_name
0    logic00001                      sma_80-2
1    logic00002                      sma_80-3
2    logic00003                      sma_80-5
3    logic00004                     sma_80-10
4    logic00005                     sma_80-20
..          ...                           ...
82   logic00083  sma_slope_5-3_macdhist_30-20
83   logic00084  sma_slope_5-3_macdhist_20-10
84   logic00085  sma_slope_3-2_macdhist_30-10
85   logic00086  sma_slope_3-2_macdhist_30-20
86   logic00087  sma_slope_3-2_macdhist_20-10

[87 rows x 2 columns]

In [334]:
MACD_signal_COL[1][

'logic00023'

In [331]:
MACD_signal_COL

[['logic00022', 'MACD_30-10', 30, 10],
 ['logic00023', 'MACD_30-20', 30, 20],
 ['logic00024', 'MACD_20-10', 20, 10]]

In [335]:
GCDC_signal_COL[1][0]

'logic00002'

In [318]:
GCDC_signal_COL

[['logic00001', 'sma_80-2', 80, 2],
 ['logic00002', 'sma_80-3', 80, 3],
 ['logic00003', 'sma_80-5', 80, 5],
 ['logic00004', 'sma_80-10', 80, 10],
 ['logic00005', 'sma_80-20', 80, 20],
 ['logic00006', 'sma_80-40', 80, 40],
 ['logic00007', 'sma_40-2', 40, 2],
 ['logic00008', 'sma_40-3', 40, 3],
 ['logic00009', 'sma_40-5', 40, 5],
 ['logic00010', 'sma_40-10', 40, 10],
 ['logic00011', 'sma_40-20', 40, 20],
 ['logic00012', 'sma_20-2', 20, 2],
 ['logic00013', 'sma_20-3', 20, 3],
 ['logic00014', 'sma_20-5', 20, 5],
 ['logic00015', 'sma_20-10', 20, 10],
 ['logic00016', 'sma_10-2', 10, 2],
 ['logic00017', 'sma_10-3', 10, 3],
 ['logic00018', 'sma_10-5', 10, 5],
 ['logic00019', 'sma_5-2', 5, 2],
 ['logic00020', 'sma_5-3', 5, 3],
 ['logic00021', 'sma_3-2', 3, 2]]

In [258]:
data_technical=MACD_signal(data_technical)
data_technical

,High,Low,Open,Close,Volume,Adj Close,macd_30-10,macdsignal_30-10,macdhist_30-10,logic00001_sell,...,macd_30-20,macdsignal_30-20,macdhist_30-20,logic00002_sell,logic00002_buy,macd_20-10,macdsignal_20-10,macdhist_20-10,logic00003_sell,logic00003_buy
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,19187.609375,18937.449219,18937.449219,19002.859375,0.0,19002.859375,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-05,19003.509766,18221.820312,19003.509766,18542.550781,0.0,18542.550781,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-06,18582.740234,18168.269531,18574.009766,18168.269531,0.0,18168.269531,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-07,18285.730469,18068.099609,18194.050781,18193.410156,0.0,18193.410156,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-11,18887.560547,18246.099609,18246.099609,18850.919922,0.0,18850.919922,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-25,29570.419922,29444.449219,29469.650391,29499.279297,50700000.0,29499.279297,201.304863,227.150311,-25.845448,False,...,96.493981,76.235202,20.258779,False,False,104.810882,134.398935,-29.588053,False,False
2021-11-26,29332.990234,28605.609375,29324.470703,28751.619141,72900000.0,28751.619141,95.010090,203.124816,-108.114726,False,...,69.050917,75.550984,-6.500068,True,False,25.959173,114.682615,-88.723442,False,False
2021-11-29,28776.339844,28187.119141,28337.960938,28283.919922,85900000.0,28283.919922,-42.324060,158.497748,-200.821807,False,...,31.030461,71.310934,-40.280473,False,False,-73.354521,80.494045,-153.848566,False,False
2021-11-30,28718.699219,27819.140625,28611.730469,27821.759766,140700000.0,27821.759766,-201.154919,93.106354,-294.261273,False,...,-15.538811,63.039530,-78.578341,False,False,-185.616108,32.110380,-217.726489,False,False
2021-12-01,28106.300781,27594.009766,27866.730469,27935.619141,80900000.0,27935.619141,-307.007880,20.358311,-327.366191,False,...,-51.361124,52.144230,-103.505354,False,False,-255.646756,-20.209099,-235.437657,False,False

In [295]:
data_technical=TrueFalseConversion(data_technical)
data_output=Data_Extraction(data=data_technical,start='2021-01-01')
data_output.to_csv('data_technical_tentative.csv')

In [362]:
data_technical=Average_SMA(data=data_technical,prices=s,window=windows)
data_technical=Average_EMA(data=data_technical,prices=s,window=windows)
data_technical=RSI(data=data_technical,prices=s,window=windows)
data_technical=bollingerBands(data=data_technical,prices=s,window=windows)
data_technical=Candlestick_entity(data_technical)
data_technical=Candlestick_size(data_technical)
data_technical=Candlestick_Yin_yang(data_technical)
data_technical=Candlestick_upper_hige(data_technical)
data_technical=Candlestick_lower_hige(data_technical)
data_technical=Candlestick_size_percentage(data_technical)
data_technical=DMI(data_technical)
data_technical=GCDC_signal(data_technical)
data_technical=MACD_signal(data_technical)
# data_technical=GCDC_MACD_signal(data_technical)
data_technical

,High,Low,Open,Close,Volume,Adj Close,sma_2,sma_3,sma_5,sma_10,...,macd_30-20,macdsignal_30-20,macdhist_30-20,logic00023_sell,logic00023_buy,macd_20-10,macdsignal_20-10,macdhist_20-10,logic00024_sell,logic00024_buy
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,19187.609375,18937.449219,18937.449219,19002.859375,0.0,19002.859375,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-05,19003.509766,18221.820312,19003.509766,18542.550781,0.0,18542.550781,18772.705078,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-06,18582.740234,18168.269531,18574.009766,18168.269531,0.0,18168.269531,18355.410156,18571.226562,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-07,18285.730469,18068.099609,18194.050781,18193.410156,0.0,18193.410156,18180.839844,18301.410156,NaN,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
2000-01-11,18887.560547,18246.099609,18246.099609,18850.919922,0.0,18850.919922,18522.165039,18404.199870,18551.601953,NaN,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-25,29570.419922,29444.449219,29469.650391,29499.279297,50700000.0,29499.279297,29400.969727,29525.349609,29584.115625,29608.165820,...,96.493981,76.235202,20.258779,False,False,104.810882,134.398935,-29.588053,False,False
2021-11-26,29332.990234,28605.609375,29324.470703,28751.619141,72900000.0,28751.619141,29125.449219,29184.519531,29414.707422,29555.541797,...,69.050917,75.550984,-6.500068,True,False,25.959173,114.682615,-88.723442,False,False
2021-11-29,28776.339844,28187.119141,28337.960938,28283.919922,85900000.0,28283.919922,28517.769531,28844.939453,29122.317578,29422.936719,...,31.030461,71.310934,-40.280473,False,False,-73.354521,80.494045,-153.848566,False,False
2021-11-30,28718.699219,27819.140625,28611.730469,27821.759766,140700000.0,27821.759766,28052.839844,28285.766276,28731.847656,29227.432617,...,-15.538811,63.039530,-78.578341,False,False,-185.616108,32.110380,-217.726489,False,False
2021-12-01,28106.300781,27594.009766,27866.730469,27935.619141,80900000.0,27935.619141,27878.689453,28013.766276,28458.439453,29040.182617,...,-51.361124,52.144230,-103.505354,False,False,-255.646756,-20.209099,-235.437657,False,False

In [310]:
GCDC_signal_COL

[['logic00001', 'sma_80-2', 80, 2],
 ['logic00002', 'sma_80-3', 80, 3],
 ['logic00003', 'sma_80-5', 80, 5],
 ['logic00004', 'sma_80-10', 80, 10],
 ['logic00005', 'sma_80-20', 80, 20],
 ['logic00006', 'sma_80-40', 80, 40],
 ['logic00007', 'sma_40-2', 40, 2],
 ['logic00008', 'sma_40-3', 40, 3],
 ['logic00009', 'sma_40-5', 40, 5],
 ['logic00010', 'sma_40-10', 40, 10],
 ['logic00011', 'sma_40-20', 40, 20],
 ['logic00012', 'sma_20-2', 20, 2],
 ['logic00013', 'sma_20-3', 20, 3],
 ['logic00014', 'sma_20-5', 20, 5],
 ['logic00015', 'sma_20-10', 20, 10],
 ['logic00016', 'sma_10-2', 10, 2],
 ['logic00017', 'sma_10-3', 10, 3],
 ['logic00018', 'sma_10-5', 10, 5],
 ['logic00019', 'sma_5-2', 5, 2],
 ['logic00020', 'sma_5-3', 5, 3],
 ['logic00021', 'sma_3-2', 3, 2]]

In [316]:
len(GCDC_signal_COL)

21

In [312]:
t=[row[3] for row in GCDC_signal_COL]
t

[2, 3, 5, 10, 20, 40, 2, 3, 5, 10, 20, 2, 3, 5, 10, 2, 3, 5, 2, 3, 2]

In [314]:
typeInfo(t)

___ は list型
___ の行数, 列数・・・(21, 1)

In [340]:
data_logic = pd.DataFrame(data_logic_complile, columns=['logic_number','logic_name'])
data_logic
# df_merge2=list(zip(data_logic_no_stack,data_logic_name_stack))
# df_merge2
# df_merge3=pd.DataFrame(df_merge2, columns=['logic_number','logic_name'])
# df_merge3

   logic_number  logic_name
0    logic00001    sma_80-2
1    logic00002    sma_80-3
2    logic00003    sma_80-5
3    logic00004   sma_80-10
4    logic00005   sma_80-20
5    logic00006   sma_80-40
6    logic00007    sma_40-2
7    logic00008    sma_40-3
8    logic00009    sma_40-5
9    logic00010   sma_40-10
10   logic00011   sma_40-20
11   logic00012    sma_20-2
12   logic00013    sma_20-3
13   logic00014    sma_20-5
14   logic00015   sma_20-10
15   logic00016    sma_10-2
16   logic00017    sma_10-3
17   logic00018    sma_10-5
18   logic00019     sma_5-2
19   logic00020     sma_5-3
20   logic00021     sma_3-2
21   logic00022  MACD_30-10
22   logic00023  MACD_30-20
23   logic00024  MACD_20-10

In [255]:
data_graph

[['logic00001', ['macd_30-10', 'macdsignal_30-10', 'macdhist_30-10']],
 ['logic00002', ['macd_30-20', 'macdsignal_30-20', 'macdhist_30-20']],
 ['logic00003', ['macd_20-10', 'macdsignal_20-10', 'macdhist_20-10']],
 ['logic00004', ['sma_80', 'sma_2']],
 ['logic00005', ['sma_80', 'sma_3']],
 ['logic00006', ['sma_80', 'sma_5']],
 ['logic00007', ['sma_80', 'sma_10']],
 ['logic00008', ['sma_80', 'sma_20']],
 ['logic00009', ['sma_80', 'sma_40']],
 ['logic00010', ['sma_40', 'sma_2']],
 ['logic00011', ['sma_40', 'sma_3']],
 ['logic00012', ['sma_40', 'sma_5']],
 ['logic00013', ['sma_40', 'sma_10']],
 ['logic00014', ['sma_40', 'sma_20']],
 ['logic00015', ['sma_20', 'sma_2']],
 ['logic00016', ['sma_20', 'sma_3']],
 ['logic00017', ['sma_20', 'sma_5']],
 ['logic00018', ['sma_20', 'sma_10']],
 ['logic00019', ['sma_10', 'sma_2']],
 ['logic00020', ['sma_10', 'sma_3']],
 ['logic00021', ['sma_10', 'sma_5']],
 ['logic00022', ['sma_5', 'sma_2']],
 ['logic00023', ['sma_5', 'sma_3']],
 ['logic00024', ['sma_3', 'sma_2']],
 ['logic00025', ['macd_30-10', 'macdsignal_30-10', 'macdhist_30-10']],
 ['logic00026', ['macd_30-20', 'macdsignal_30-20', 'macdhist_30-20']],
 ['logic00027', ['macd_20-10', 'macdsignal_20-10', 'macdhist_20-10']]]

In [ ]:
# 変数名をそのままprint関数内で表示させる関数
def chkprint(*args):
    for obj in args:
        for k, v in globals().items():
            if id(v) == id(obj):
                target = k
                break          
    return target

# データがどのデータ型か、列数、行数を表示する関数
def typeInfo(targetData):
    if (type(targetData) is pd.core.frame.DataFrame):
        print("{} は DataFrame型".format(chkprint(targetData)))
        print("{} の行数, 列数・・・{}\n".format(chkprint(targetData), targetData.shape))     # shapeの表示内容は、(行数, 列数)となる
    if (type(targetData) is list):
        print("{} は list型".format(chkprint(targetData)))
        print("{} の行数, 列数・・・{}\n".format(chkprint(targetData), pd.DataFrame(targetData).shape))    # shapeの表示内容は、(行数, 列数)となる
    if (type(targetData) is np.ndarray):
        print("{} は ndarray型".format(chkprint(targetData)))
        print("{} の行数, 列数・・・{}\n".format(chkprint(targetData), targetData.shape))     # shapeの表示内容は、(行数, 列数)となる
    if (type(targetData) is pd.core.series.Series):
        print("{} は Series型".format(chkprint(targetData)))
        print("{} の行数, 列数・・・{}\n".format(chkprint(targetData), targetData.shape))     # shapeの表示内容は、(行数, 列数)となる

◆Box1.1 P.22
　終値が移動平均を上回ったら買え

moving average(type, price, length)

→moving average(simple,close,21)

◆やりたいこと
市場が200日移動平均を上回って引け、その後下落トレンドに転じ、RSIが20を下回って底を付け、その後上昇し始めたら買え。売りは逆。

今日の終値が終値の200日移動平均を上回り、今日の終値が昨日の終値を下回り、昨日の終値がその前日の終値を下回り、その前日の終値がそのまた前日の終値を下回り、昨日の14日RSIが20を下回り、昨日の14日RSIが今日の14日RSI を下回ったとき、成り行きで買う。

if close> 200 day moving average and
close くclose[1] and close [1] < close [2] and
close[2］くclose[3] and yesterday’s 14 day RSI ＜ 20 and
yesterday’s 14 day RSI くtoday’s 14 day RSI then BUY

P27:最初の不等号が逆な気がする

In [ ]:
if myClose[DO] < sAverage(myClose,200,DO,1) and 
myClose[DO]<myClose[D1] and myClose[D2]くmyClose[D3] and
myClose[D1]<myClose[D2] and 
rsiVal[D1] < 20 and rsiVal[D1]<rsiVal[DO]:

buyEntryName: 'rsiBuy'
entryPrice = myOpen